### ISSUE TITLE
Please upgrade to nan2 (iojs 3.0)

### ISSUE THREAD

**Issue by matylla** [dberesford/exiv2node#37]
Currently It's not possible to build the module on iojs 3.0. Please upgrade the code for nan2

````
> exiv2@0.6.0 install /Users/matylla/Kraken/cluster/node_modules/exiv2
> node-gyp rebuild

  CXX(target) Release/obj.target/exiv2/exiv2node.o
In file included from ../exiv2node.cc:4:
../node_modules/nan/nan.h:324:27: error: redefinition of 'NanEnsureHandleOrPersistent'
  NAN_INLINE v8::Local<T> NanEnsureHandleOrPersistent(const v8::Local<T> &val) 
````

**Comment by drewish** [comment]
Please use the master branch. There should be a release before too long.

**Comment by skerit** [comment]
Any idea when that update is coming?

**Comment by matylla** [comment]
The update is there in the repo, it's just not published to npm yet. You can install the package directly from GitHub like so:

`npm install dberesford/exiv2node --save`

**Comment by drewish** [comment]
@dberesford what version do you want to use for this release?

**Comment by dberesford** [comment]
1.0.0 ok with you? (finally!) :-)

**Comment by drewish** [comment]
I realized we hadn't changed anything other than supporting the new version of node so I just went with 0.6.1 (and created a tag for 0.6.0 since that was missing)
