### ISSUE TITLE
Unable to Extract Exif from PhaseOne IIQ file 

### ISSUE THREAD

**Issue by lensupthere** [dberesford/exiv2node#51]
I am working with Phase One IIQ images.

The issue is: I can use the command line to use exiv2 to retrieve specific exif tags, but not exiv2node to do the same.

Using Exiv2 from the command line, extracting specific exif data works fine using exiv2 ... 
e.g. 'exiv2 -px -g GPSLatitude SkyIMD_20692.IIQ'
response: 'Xmp.exif.GPSLatitude XmpText 13 37,23.716896N'

I'm building an electron  app, the getImageTags() function fails to do anything and I am unable to parse any exif data. I am following the examples here/GitHub

Image file is here: ﻿﻿﻿https://www.dropbox.com/s/vaaduxlr4u07zgo/SkyIMD_20692.IIQ?dl=0

If I run the same code on a group of JPG images from a Canon camera, everything is fine. If I run the same code on IIQ images converted to JPG's, everything is fine.

Any help would be appreciated.

thanks.

**Comment by dberesford** [comment]
Hi @lensupthere, it looks like it's having a problem with the [makernote](http://www.exiv2.org/makernote.html) field in the image. Exiv2-node returns all the tags and their values by default, and the value for this tag looks to be an unending sequence of bytes that eventually blows up the memory. 

If we look at this tag in exiv2 (using -pa) we see it's not one of the makernotes that exiv2 knows about:

```
$ exiv2 -pa test/images/sky.iiq |grep -i maker
Exif.Photo.MakerNote                         Undefined 116821540  (Binary value suppressed)
```

So obviously exiv2 doesn't blow up when it encounters this tag, but it's currently unclear what it's passing back to exiv2-node that makes it behave like this.

**Comment by lensupthere** [comment]
Thanks for the response, also read the comments between you and Robin.  I included Robin on an email to Phase One.
